In [11]:
import pandas as pd
import os
os.chdir('..')
os.chdir('01_Data_Collection') 
os.chdir('01A_External_Data')

In [12]:
csv_file_path = 'resale-flat-prices-full-version.csv'
df = pd.read_csv(csv_file_path)

# Display the first few rows of the DataFrame to verify import
df.head()

,tranc_yearmonth,town,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,lease_commence_date,resale_price,...,bus_stop_nearest_distance,bus_stop_name,pri_sch_nearest_distance,pri_sch_name,vacancy,pri_sch_affiliation,sec_sch_nearest_dist,sec_sch_name,cutoff_point,affiliation
0,2016-05-01,KALLANG/WHAMPOA,4 ROOM,3B,UPP BOON KENG RD,10 TO 12,90.0,Model A,2006,680000.0,...,29.427395,Blk 3B,1138.633422,Geylang Methodist School,78,1,1138.633422,Geylang Methodist School,224,0
1,2012-07-01,BISHAN,5 ROOM,153,BISHAN ST 13,07 TO 09,130.0,Improved,1987,665000.0,...,58.207761,BLK 151A MKT,415.607357,Kuo Chuan Presbyterian Primary School,45,1,447.894399,Kuo Chuan Presbyterian Secondary School,232,0
2,2013-07-01,BUKIT BATOK,EXECUTIVE,289B,BT BATOK ST 25,13 TO 15,144.0,Apartment,1997,838000.0,...,214.747860,Blk 289E,498.849039,Keming Primary School,39,0,180.074558,Yusof Ishak Secondary School,188,0
3,2012-04-01,BISHAN,4 ROOM,232,BISHAN ST 22,01 TO 05,103.0,Model A,1992,550000.0,...,43.396521,Opp Bishan Nth Shop Mall,389.515528,Catholic High School,20,1,389.515528,Catholic High School,253,1
4,2017-12-01,YISHUN,4 ROOM,876,YISHUN ST 81,01 TO 03,83.0,Simplified,1987,298000.0,...,129.422752,Blk 873,401.200584,Naval Base Primary School,74,0,312.025435,Orchid Park Secondary School,208,0

In [13]:
# Get the list of all column names
column_names = df.columns.tolist()

# Display each column name on a separate row
for name in column_names:
    print(name)

tranc_yearmonth
town
flat_type
block
street_name
storey_range
floor_area_sqm
flat_model
lease_commence_date
resale_price
tranc_year
tranc_month
mid_storey
full_flat_type
address
max_floor_lvl
commercial
market_hawker
multistorey_carpark
precinct_pavilion
total_dwelling_units
postal
planning_area
mall_nearest_distance
hawker_nearest_distance
hawker_food_stalls
hawker_market_stalls
mrt_nearest_distance
mrt_name
bus_interchange
mrt_interchange
bus_stop_nearest_distance
bus_stop_name
pri_sch_nearest_distance
pri_sch_name
vacancy
pri_sch_affiliation
sec_sch_nearest_dist
sec_sch_name
cutoff_point
affiliation

resale_price: the property's sale price in Singapore dollars. This is the target variable that you're trying to predict for this challenge. <br>
Tranc_YearMonth: year and month of the resale transaction, e.g. 2015-02 <br>
town: HDB township where the flat is located, e.g. BUKIT MERAH<br>
flat_type: type of the resale flat unit, e.g. 3 ROOM<br>
block: block number of the resale flat, e.g. 454<br>
street_name: street name where the resale flat resides, e.g. TAMPINES ST 42<br>
storey_range: floor level (range) of the resale flat unit, e.g. 07 TO 09<br>
floor_area_sqm: floor area of the resale flat unit in square metres<br>
flat_model: HDB model of the resale flat, e.g. Multi Generation<br>
lease_commence_date: commencement year of the flat unit's 99-year lease<br>
Tranc_Year: year of resale transaction<br>
Tranc_Month: month of resale transaction<br>
mid_storey: median value of storey_range<br>
full_flat_type: combination of flat_type and flat_model<br>
address: combination of block and street_name<br>
max_floor_lvl: highest floor of the resale flat<br>
commercial: boolean value if resale flat has commercial units in the same block<br>
market_hawker: boolean value if resale flat has a market or hawker centre in the same block<br>
multistorey_carpark: boolean value if resale flat has a multistorey carpark in the same block<br>
precinct_pavilion: boolean value if resale flat has a pavilion in the same block<br>
total_dwelling_units: total number of residential dwelling units in the resale flat<br>
postal: postal code of the resale flat block<br>
planning_area: Government planning area that the flat is located<br>
Mall_Nearest_Distance: distance (in metres) to the nearest mall<br>
Hawker_Nearest_Distance: distance (in metres) to the nearest hawker centre<br>
hawker_food_stalls: number of hawker food stalls in the nearest hawker centre<br>
hawker_market_stalls: number of hawker and market stalls in the nearest hawker centre<br>
mrt_nearest_distance: distance (in metres) to the nearest MRT station<br>
mrt_name: name of the nearest MRT station<br>
bus_interchange: boolean value if the nearest MRT station is also a bus interchange<br>
mrt_interchange: boolean value if the nearest MRT station is a train interchange station<br>
bus_stop_nearest_distance: distance (in metres) to the nearest bus stop<br>
bus_stop_name: name of the nearest bus stop<br>
pri_sch_nearest_distance: distance (in metres) to the nearest primary school<br>
pri_sch_name: name of the nearest primary school<br>
vacancy: number of vacancies in the nearest primary school<br>
pri_sch_affiliation: boolean value if the nearest primary school has a secondary school affiliation<br>
sec_sch_nearest_dist: distance (in metres) to the nearest secondary school<br>
sec_sch_name: name of the nearest secondary school<br>
cutoff_point: PSLE cutoff point of the nearest secondary school<br>
affiliation: boolean value if the nearest secondary school has an primary school affiliation<br>

In [14]:
# Find the number of distinct addresses in the DataFrame
num_distinct_addresses = df['address'].nunique()

# Print the number of distinct addresses
print("Number of distinct addresses:", num_distinct_addresses)

Number of distinct addresses: 9013

In [15]:
# Select columns 14 to 41 from the original DataFrame
feature_dict = df.iloc[:, [14] + list(range(16, 41))]

# Display the sub DataFrame
feature_dict.head()

,address,commercial,market_hawker,multistorey_carpark,precinct_pavilion,total_dwelling_units,postal,planning_area,mall_nearest_distance,hawker_nearest_distance,...,bus_stop_nearest_distance,bus_stop_name,pri_sch_nearest_distance,pri_sch_name,vacancy,pri_sch_affiliation,sec_sch_nearest_dist,sec_sch_name,cutoff_point,affiliation
0,"3B, UPP BOON KENG RD",0,0,0,0,142,382003,Kallang,1094.090418,154.753357,...,29.427395,Blk 3B,1138.633422,Geylang Methodist School,78,1,1138.633422,Geylang Methodist School,224,0
1,"153, BISHAN ST 13",0,0,0,0,112,570153,Bishan,866.941448,640.151925,...,58.207761,BLK 151A MKT,415.607357,Kuo Chuan Presbyterian Primary School,45,1,447.894399,Kuo Chuan Presbyterian Secondary School,232,0
2,"289B, BT BATOK ST 25",0,0,0,0,90,651289,Bukit Batok,1459.579948,1762.082341,...,214.747860,Blk 289E,498.849039,Keming Primary School,39,0,180.074558,Yusof Ishak Secondary School,188,0
3,"232, BISHAN ST 22",1,0,0,0,75,570232,Bishan,950.175199,726.215262,...,43.396521,Opp Bishan Nth Shop Mall,389.515528,Catholic High School,20,1,389.515528,Catholic High School,253,1
4,"876, YISHUN ST 81",0,0,0,0,48,760876,Yishun,729.771895,1540.151439,...,129.422752,Blk 873,401.200584,Naval Base Primary School,74,0,312.025435,Orchid Park Secondary School,208,0

In [16]:
# Remove duplicate rows from the DataFrame
feature_dict_no_duplicates = feature_dict.drop_duplicates()

print(len(feature_dict_no_duplicates))

# Display the DataFrame after removing duplicates
feature_dict_no_duplicates.head()

9013

,address,commercial,market_hawker,multistorey_carpark,precinct_pavilion,total_dwelling_units,postal,planning_area,mall_nearest_distance,hawker_nearest_distance,...,bus_stop_nearest_distance,bus_stop_name,pri_sch_nearest_distance,pri_sch_name,vacancy,pri_sch_affiliation,sec_sch_nearest_dist,sec_sch_name,cutoff_point,affiliation
0,"3B, UPP BOON KENG RD",0,0,0,0,142,382003,Kallang,1094.090418,154.753357,...,29.427395,Blk 3B,1138.633422,Geylang Methodist School,78,1,1138.633422,Geylang Methodist School,224,0
1,"153, BISHAN ST 13",0,0,0,0,112,570153,Bishan,866.941448,640.151925,...,58.207761,BLK 151A MKT,415.607357,Kuo Chuan Presbyterian Primary School,45,1,447.894399,Kuo Chuan Presbyterian Secondary School,232,0
2,"289B, BT BATOK ST 25",0,0,0,0,90,651289,Bukit Batok,1459.579948,1762.082341,...,214.747860,Blk 289E,498.849039,Keming Primary School,39,0,180.074558,Yusof Ishak Secondary School,188,0
3,"232, BISHAN ST 22",1,0,0,0,75,570232,Bishan,950.175199,726.215262,...,43.396521,Opp Bishan Nth Shop Mall,389.515528,Catholic High School,20,1,389.515528,Catholic High School,253,1
4,"876, YISHUN ST 81",0,0,0,0,48,760876,Yishun,729.771895,1540.151439,...,129.422752,Blk 873,401.200584,Naval Base Primary School,74,0,312.025435,Orchid Park Secondary School,208,0

In [17]:
os.chdir('..')
os.chdir('..')
os.chdir('02_Data_Processing') 

# Get the current working directory
current_directory = os.getcwd()

# Print the current working directory
print("Current working directory:", current_directory)

Current working directory: /Users/renzhou/Downloads/Y3S2/IS3107/Data-Engine/ETL/02_Data_Processing

In [21]:
# Define the file path for the CSV file
csv_file_path = 'feature_dict.csv'

# Export the DataFrame to a CSV file
feature_dict_no_duplicates.to_csv(csv_file_path, index=False)

In [19]:
# # Initialize an empty dictionary
# feature_dict = {}

# # Iterate over the DataFrame
# for index, row in df.iterrows():
#     key = row['address']   # Taking value from the 'address' column as the key
#     values_list = row[15:41].tolist()  # Extract values from columns 15 to 40 as a list
#     feature_dict[key] = values_list  # Setting key-value pair in the dictionary

# # Access the first item of feature_dict
# first_item_key = list(feature_dict.keys())[0]
# first_item_value = feature_dict[first_item_key]

# # Display the first item
# print("Key:", first_item_key)
# print("Value:", first_item_value)

# print(len(feature_dict))

In [20]:

# # Convert feature_dict to a DataFrame
# feature_df = pd.DataFrame.from_dict(feature_dict, orient='index')

# # Define the file path for the CSV file
# csv_file_path = 'feature_dict.csv'

# # Export the DataFrame to a CSV file
# feature_df.to_csv(csv_file_path)